# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class GoalsVendorData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id_goal: int=None, id_user: int=None, internet_dolar: float=None, internet_volumen: int=None, telefonia_dolar: float=None, telefonia_volumen: int=None, television_dolar: float=None, television_volumen: int=None, goal_date: str=None, created_at: datetime=None):  # noqa: E501
        """GoalsVendorData - a model defined in Swagger

        :param id_goal: The id_goal of this GoalsVendorData.  # noqa: E501
        :type id_goal: int
        :param id_user: The id_user of this GoalsVendorData.  # noqa: E501
        :type id_user: int
        :param internet_dolar: The internet_dolar of this GoalsVendorData.  # noqa: E501
        :type internet_dolar: float
        :param internet_volumen: The internet_volumen of this GoalsVendorData.  # noqa: E501
        :type internet_volumen: int
        :param telefonia_dolar: The telefonia_dolar of this GoalsVendorData.  # noqa: E501
        :type telefonia_dolar: float
        :param telefonia_volumen: The telefonia_volumen of this GoalsVendorData.  # noqa: E501
        :type telefonia_volumen: int
        :param television_dolar: The television_dolar of this GoalsVendorData.  # noqa: E501
        :type television_dolar: float
        :param television_volumen: The television_volumen of this GoalsVendorData.  # noqa: E501
        :type television_volumen: int
        :param goal_date: The goal_date of this GoalsVendorData.  # noqa: E501
        :type goal_date: str
        :param created_at: The created_at of this GoalsVendorData.  # noqa: E501
        :type created_at: datetime
        """
        self.swagger_types = {
            'id_goal': int,
            'id_user': int,
            'internet_dolar': float,
            'internet_volumen': int,
            'telefonia_dolar': float,
            'telefonia_volumen': int,
            'television_dolar': float,
            'television_volumen': int,
            'goal_date': str,
            'created_at': datetime
        }

        self.attribute_map = {
            'id_goal': 'id_goal',
            'id_user': 'id_user',
            'internet_dolar': 'internet_dolar',
            'internet_volumen': 'internet_volumen',
            'telefonia_dolar': 'telefonia_dolar',
            'telefonia_volumen': 'telefonia_volumen',
            'television_dolar': 'television_dolar',
            'television_volumen': 'television_volumen',
            'goal_date': 'goal_date',
            'created_at': 'created_at'
        }
        self._id_goal = id_goal
        self._id_user = id_user
        self._internet_dolar = internet_dolar
        self._internet_volumen = internet_volumen
        self._telefonia_dolar = telefonia_dolar
        self._telefonia_volumen = telefonia_volumen
        self._television_dolar = television_dolar
        self._television_volumen = television_volumen
        self._goal_date = goal_date
        self._created_at = created_at

    @classmethod
    def from_dict(cls, dikt) -> 'GoalsVendorData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GoalsVendorData of this GoalsVendorData.  # noqa: E501
        :rtype: GoalsVendorData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id_goal(self) -> int:
        """Gets the id_goal of this GoalsVendorData.


        :return: The id_goal of this GoalsVendorData.
        :rtype: int
        """
        return self._id_goal

    @id_goal.setter
    def id_goal(self, id_goal: int):
        """Sets the id_goal of this GoalsVendorData.


        :param id_goal: The id_goal of this GoalsVendorData.
        :type id_goal: int
        """

        self._id_goal = id_goal

    @property
    def id_user(self) -> int:
        """Gets the id_user of this GoalsVendorData.


        :return: The id_user of this GoalsVendorData.
        :rtype: int
        """
        return self._id_user

    @id_user.setter
    def id_user(self, id_user: int):
        """Sets the id_user of this GoalsVendorData.


        :param id_user: The id_user of this GoalsVendorData.
        :type id_user: int
        """

        self._id_user = id_user

    @property
    def internet_dolar(self) -> float:
        """Gets the internet_dolar of this GoalsVendorData.


        :return: The internet_dolar of this GoalsVendorData.
        :rtype: float
        """
        return self._internet_dolar

    @internet_dolar.setter
    def internet_dolar(self, internet_dolar: float):
        """Sets the internet_dolar of this GoalsVendorData.


        :param internet_dolar: The internet_dolar of this GoalsVendorData.
        :type internet_dolar: float
        """

        self._internet_dolar = internet_dolar

    @property
    def internet_volumen(self) -> int:
        """Gets the internet_volumen of this GoalsVendorData.


        :return: The internet_volumen of this GoalsVendorData.
        :rtype: int
        """
        return self._internet_volumen

    @internet_volumen.setter
    def internet_volumen(self, internet_volumen: int):
        """Sets the internet_volumen of this GoalsVendorData.


        :param internet_volumen: The internet_volumen of this GoalsVendorData.
        :type internet_volumen: int
        """

        self._internet_volumen = internet_volumen

    @property
    def telefonia_dolar(self) -> float:
        """Gets the telefonia_dolar of this GoalsVendorData.


        :return: The telefonia_dolar of this GoalsVendorData.
        :rtype: float
        """
        return self._telefonia_dolar

    @telefonia_dolar.setter
    def telefonia_dolar(self, telefonia_dolar: float):
        """Sets the telefonia_dolar of this GoalsVendorData.


        :param telefonia_dolar: The telefonia_dolar of this GoalsVendorData.
        :type telefonia_dolar: float
        """

        self._telefonia_dolar = telefonia_dolar

    @property
    def telefonia_volumen(self) -> int:
        """Gets the telefonia_volumen of this GoalsVendorData.


        :return: The telefonia_volumen of this GoalsVendorData.
        :rtype: int
        """
        return self._telefonia_volumen

    @telefonia_volumen.setter
    def telefonia_volumen(self, telefonia_volumen: int):
        """Sets the telefonia_volumen of this GoalsVendorData.


        :param telefonia_volumen: The telefonia_volumen of this GoalsVendorData.
        :type telefonia_volumen: int
        """

        self._telefonia_volumen = telefonia_volumen

    @property
    def television_dolar(self) -> float:
        """Gets the television_dolar of this GoalsVendorData.


        :return: The television_dolar of this GoalsVendorData.
        :rtype: float
        """
        return self._television_dolar

    @television_dolar.setter
    def television_dolar(self, television_dolar: float):
        """Sets the television_dolar of this GoalsVendorData.


        :param television_dolar: The television_dolar of this GoalsVendorData.
        :type television_dolar: float
        """

        self._television_dolar = television_dolar

    @property
    def television_volumen(self) -> int:
        """Gets the television_volumen of this GoalsVendorData.


        :return: The television_volumen of this GoalsVendorData.
        :rtype: int
        """
        return self._television_volumen

    @television_volumen.setter
    def television_volumen(self, television_volumen: int):
        """Sets the television_volumen of this GoalsVendorData.


        :param television_volumen: The television_volumen of this GoalsVendorData.
        :type television_volumen: int
        """

        self._television_volumen = television_volumen

    @property
    def goal_date(self) -> str:
        """Gets the goal_date of this GoalsVendorData.


        :return: The goal_date of this GoalsVendorData.
        :rtype: str
        """
        return self._goal_date

    @goal_date.setter
    def goal_date(self, goal_date: str):
        """Sets the goal_date of this GoalsVendorData.


        :param goal_date: The goal_date of this GoalsVendorData.
        :type goal_date: str
        """

        self._goal_date = goal_date

    @property
    def created_at(self) -> datetime:
        """Gets the created_at of this GoalsVendorData.


        :return: The created_at of this GoalsVendorData.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: datetime):
        """Sets the created_at of this GoalsVendorData.


        :param created_at: The created_at of this GoalsVendorData.
        :type created_at: datetime
        """

        self._created_at = created_at
