# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RequestGetSingleGoalsVendor(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, channel: str=None, externalTransactionId: str=None, id_user: int=None, id_goal: int=None):  # noqa: E501
        """RequestGetSingleGoalsVendor - a model defined in Swagger

        :param channel: The channel of this RequestGetSingleGoalsVendor.  # noqa: E501
        :type channel: str
        :param externalTransactionId: The externalTransactionId of this RequestGetSingleGoalsVendor.  # noqa: E501
        :type externalTransactionId: str
        :param id_user: The id_user of this RequestGetSingleGoalsVendor.  # noqa: E501
        :type id_user: int
        :param id_goal: The id_goal of this RequestGetSingleGoalsVendor.  # noqa: E501
        :type id_goal: int
        """
        self.swagger_types = {
            'channel': str,
            'externalTransactionId': str,
            'id_user': int,
            'id_goal': int
        }

        self.attribute_map = {
            'channel': 'channel',
            'externalTransactionId': 'externalTransactionId',
            'id_user': 'id_user',
            'id_goal': 'id_goal'
        }
        self._channel = channel
        self._externalTransactionId = externalTransactionId
        self._id_user = id_user
        self._id_goal = id_goal

    @classmethod
    def from_dict(cls, dikt) -> 'RequestGetSingleGoalsVendor':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestGetSingleGoalsVendor of this RequestGetSingleGoalsVendor.  # noqa: E501
        :rtype: RequestGetSingleGoalsVendor
        """
        return util.deserialize_model(dikt, cls)

    @property
    def channel(self) -> str:
        """Gets the channel of this RequestGetSingleGoalsVendor.


        :return: The channel of this RequestGetSingleGoalsVendor.
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel: str):
        """Sets the channel of this RequestGetSingleGoalsVendor.


        :param channel: The channel of this RequestGetSingleGoalsVendor.
        :type channel: str
        """

        self._channel = channel

    @property
    def externalTransactionId(self) -> str:
        """Gets the externalTransactionId of this RequestGetSingleGoalsVendor.


        :return: The externalTransactionId of this RequestGetSingleGoalsVendor.
        :rtype: str
        """
        return self._externalTransactionId

    @externalTransactionId.setter
    def externalTransactionId(self, externalTransactionId: str):
        """Sets the externalTransactionId of this RequestGetSingleGoalsVendor.


        :param externalTransactionId: The externalTransactionId of this RequestGetSingleGoalsVendor.
        :type externalTransactionId: str
        """

        self._externalTransactionId = externalTransactionId

    @property
    def id_user(self) -> int:
        """Gets the id_user of this RequestGetSingleGoalsVendor.


        :return: The id_user of this RequestGetSingleGoalsVendor.
        :rtype: int
        """
        return self._id_user

    @id_user.setter
    def id_user(self, id_user: int):
        """Sets the id_user of this RequestGetSingleGoalsVendor.


        :param id_user: The id_user of this RequestGetSingleGoalsVendor.
        :type id_user: int
        """

        self._id_user = id_user

    @property
    def id_goal(self) -> int:
        """Gets the id_goal of this RequestGetSingleGoalsVendor.


        :return: The id_goal of this RequestGetSingleGoalsVendor.
        :rtype: int
        """
        return self._id_goal

    @id_goal.setter
    def id_goal(self, id_goal: int):
        """Sets the id_goal of this RequestGetSingleGoalsVendor.


        :param id_goal: The id_goal of this RequestGetSingleGoalsVendor.
        :type id_goal: int
        """

        self._id_goal = id_goal
