# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.goals_vendor_data import GoalsVendorData  # noqa: F401,E501
from swagger_server import util


class RequestNewGoalsVendor(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, channel: str=None, externalTransactionId: str=None, data: GoalsVendorData=None):  # noqa: E501
        """RequestNewGoalsVendor - a model defined in Swagger

        :param channel: The channel of this RequestNewGoalsVendor.  # noqa: E501
        :type channel: str
        :param externalTransactionId: The externalTransactionId of this RequestNewGoalsVendor.  # noqa: E501
        :type externalTransactionId: str
        :param data: The data of this RequestNewGoalsVendor.  # noqa: E501
        :type data: GoalsVendorData
        """
        self.swagger_types = {
            'channel': str,
            'externalTransactionId': str,
            'data': GoalsVendorData
        }

        self.attribute_map = {
            'channel': 'channel',
            'externalTransactionId': 'externalTransactionId',
            'data': 'data'
        }
        self._channel = channel
        self._externalTransactionId = externalTransactionId
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'RequestNewGoalsVendor':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestNewGoalsVendor of this RequestNewGoalsVendor.  # noqa: E501
        :rtype: RequestNewGoalsVendor
        """
        return util.deserialize_model(dikt, cls)

    @property
    def channel(self) -> str:
        """Gets the channel of this RequestNewGoalsVendor.


        :return: The channel of this RequestNewGoalsVendor.
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel: str):
        """Sets the channel of this RequestNewGoalsVendor.


        :param channel: The channel of this RequestNewGoalsVendor.
        :type channel: str
        """

        self._channel = channel

    @property
    def externalTransactionId(self) -> str:
        """Gets the externalTransactionId of this RequestNewGoalsVendor.


        :return: The externalTransactionId of this RequestNewGoalsVendor.
        :rtype: str
        """
        return self._externalTransactionId

    @externalTransactionId.setter
    def externalTransactionId(self, externalTransactionId: str):
        """Sets the externalTransactionId of this RequestNewGoalsVendor.


        :param externalTransactionId: The externalTransactionId of this RequestNewGoalsVendor.
        :type externalTransactionId: str
        """

        self._externalTransactionId = externalTransactionId

    @property
    def data(self) -> GoalsVendorData:
        """Gets the data of this RequestNewGoalsVendor.


        :return: The data of this RequestNewGoalsVendor.
        :rtype: GoalsVendorData
        """
        return self._data

    @data.setter
    def data(self, data: GoalsVendorData):
        """Sets the data of this RequestNewGoalsVendor.


        :param data: The data of this RequestNewGoalsVendor.
        :type data: GoalsVendorData
        """

        self._data = data
