# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RequestGetAllGoalsVendor(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, channel: str=None, externalTransactionId: str=None, id_user: int=None, goal_date: str=None):  # noqa: E501
        """RequestGetAllGoalsVendor - a model defined in Swagger

        :param channel: The channel of this RequestGetAllGoalsVendor.  # noqa: E501
        :type channel: str
        :param externalTransactionId: The externalTransactionId of this RequestGetAllGoalsVendor.  # noqa: E501
        :type externalTransactionId: str
        :param id_user: The id_user of this RequestGetAllGoalsVendor.  # noqa: E501
        :type id_user: int
        :param goal_date: The goal_date of this RequestGetAllGoalsVendor.  # noqa: E501
        :type goal_date: str
        """
        self.swagger_types = {
            'channel': str,
            'externalTransactionId': str,
            'id_user': int,
            'goal_date': str
        }

        self.attribute_map = {
            'channel': 'channel',
            'externalTransactionId': 'externalTransactionId',
            'id_user': 'id_user',
            'goal_date': 'goal_date'
        }
        self._channel = channel
        self._externalTransactionId = externalTransactionId
        self._id_user = id_user
        self._goal_date = goal_date

    @classmethod
    def from_dict(cls, dikt) -> 'RequestGetAllGoalsVendor':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestGetAllGoalsVendor of this RequestGetAllGoalsVendor.  # noqa: E501
        :rtype: RequestGetAllGoalsVendor
        """
        return util.deserialize_model(dikt, cls)

    @property
    def channel(self) -> str:
        """Gets the channel of this RequestGetAllGoalsVendor.


        :return: The channel of this RequestGetAllGoalsVendor.
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel: str):
        """Sets the channel of this RequestGetAllGoalsVendor.


        :param channel: The channel of this RequestGetAllGoalsVendor.
        :type channel: str
        """

        self._channel = channel

    @property
    def externalTransactionId(self) -> str:
        """Gets the externalTransactionId of this RequestGetAllGoalsVendor.


        :return: The externalTransactionId of this RequestGetAllGoalsVendor.
        :rtype: str
        """
        return self._externalTransactionId

    @externalTransactionId.setter
    def externalTransactionId(self, externalTransactionId: str):
        """Sets the externalTransactionId of this RequestGetAllGoalsVendor.


        :param externalTransactionId: The externalTransactionId of this RequestGetAllGoalsVendor.
        :type externalTransactionId: str
        """

        self._externalTransactionId = externalTransactionId

    @property
    def id_user(self) -> int:
        """Gets the id_user of this RequestGetAllGoalsVendor.


        :return: The id_user of this RequestGetAllGoalsVendor.
        :rtype: int
        """
        return self._id_user

    @id_user.setter
    def id_user(self, id_user: int):
        """Sets the id_user of this RequestGetAllGoalsVendor.


        :param id_user: The id_user of this RequestGetAllGoalsVendor.
        :type id_user: int
        """

        self._id_user = id_user

    @property
    def goal_date(self) -> str:
        """Gets the goal_date of this RequestGetAllGoalsVendor.


        :return: The goal_date of this RequestGetAllGoalsVendor.
        :rtype: str
        """
        return self._goal_date

    @goal_date.setter
    def goal_date(self, goal_date: str):
        """Sets the goal_date of this RequestGetAllGoalsVendor.


        :param goal_date: The goal_date of this RequestGetAllGoalsVendor.
        :type goal_date: str
        """

        self._goal_date = goal_date
