# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.goals_vendor_data import GoalsVendorData  # noqa: F401,E501
from swagger_server import util


class ResponseNewGoalsVendor(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, code: str=None, channel: str=None, message: str=None, externalTransactionId: str=None, internalTransactionId: str=None, data: GoalsVendorData=None):  # noqa: E501
        """ResponseNewGoalsVendor - a model defined in Swagger

        :param channel: The channel of this ResponseNewGoalsVendor.  # noqa: E501
        :type channel: str
        :param externalTransactionId: The externalTransactionId of this ResponseNewGoalsVendor.  # noqa: E501
        :type externalTransactionId: str
        :param internalTransactionId: The internalTransactionId of this ResponseNewGoalsVendor.  # noqa: E501
        :type internalTransactionId: str
        :param data: The data of this ResponseNewGoalsVendor.  # noqa: E501
        :type data: GoalsVendorData
        """
        self.swagger_types = {
            'code': str,
            'channel': str,
            'externalTransactionId': str,
            'internalTransactionId': str,
            'data': GoalsVendorData,
            'message': str
            
        }

        self.attribute_map = {
            'code': 'code',
            'channel': 'channel',
            'externalTransactionId': 'externalTransactionId',
            'internalTransactionId': 'internalTransactionId',
            'data': 'data',
            'message': 'message'
        }
        self._code = code
        self._channel = channel
        self._externalTransactionId = externalTransactionId
        self._internalTransactionId = internalTransactionId
        self._message = message
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseNewGoalsVendor':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseNewGoalsVendor of this ResponseNewGoalsVendor.  # noqa: E501
        :rtype: ResponseNewGoalsVendor
        """
        return util.deserialize_model(dikt, cls)
    
    @property
    def code(self) -> str:
        """Gets the code of this ResponseDeleteAddress.


        :return: The code of this ResponseDeleteAddress.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code: str):
        """Sets the code of this ResponseDeleteAddress.


        :param code: The code of this ResponseDeleteAddress.
        :type code: str
        """

        self._code = code

    @property
    def channel(self) -> str:
        """Gets the channel of this ResponseNewGoalsVendor.


        :return: The channel of this ResponseNewGoalsVendor.
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel: str):
        """Sets the channel of this ResponseNewGoalsVendor.


        :param channel: The channel of this ResponseNewGoalsVendor.
        :type channel: str
        """

        self._channel = channel

    @property
    def externalTransactionId(self) -> str:
        """Gets the externalTransactionId of this ResponseNewGoalsVendor.


        :return: The externalTransactionId of this ResponseNewGoalsVendor.
        :rtype: str
        """
        return self._externalTransactionId

    @externalTransactionId.setter
    def externalTransactionId(self, externalTransactionId: str):
        """Sets the externalTransactionId of this ResponseNewGoalsVendor.


        :param externalTransactionId: The externalTransactionId of this ResponseNewGoalsVendor.
        :type externalTransactionId: str
        """

        self._externalTransactionId = externalTransactionId

    @property
    def internalTransactionId(self) -> str:
        """Gets the internalTransactionId of this ResponseNewGoalsVendor.


        :return: The internalTransactionId of this ResponseNewGoalsVendor.
        :rtype: str
        """
        return self._internalTransactionId

    @internalTransactionId.setter
    def internalTransactionId(self, internalTransactionId: str):
        """Sets the internalTransactionId of this ResponseNewGoalsVendor.


        :param internalTransactionId: The internalTransactionId of this ResponseNewGoalsVendor.
        :type internalTransactionId: str
        """

        self._internalTransactionId = internalTransactionId


    @property
    def message(self) -> str:
        """Gets the message of this ResponseDeleteAddress.


        :return: The message of this ResponseDeleteAddress.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ResponseDeleteAddress.


        :param message: The message of this ResponseDeleteAddress.
        :type message: str
        """

        self._message = message    

    @property
    def data(self) -> GoalsVendorData:
        """Gets the data of this ResponseNewGoalsVendor.


        :return: The data of this ResponseNewGoalsVendor.
        :rtype: GoalsVendorData
        """
        return self._data

    @data.setter
    def data(self, data: GoalsVendorData):
        """Sets the data of this ResponseNewGoalsVendor.


        :param data: The data of this ResponseNewGoalsVendor.
        :type data: GoalsVendorData
        """

        self._data = data
